<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <ul>
      <li :key="m.id" v-for="m in menus" @click="getId(m.id)">
        {{ m.value }}
      </li>
    </ul>
    <Button type="primary" @click="click">btn</Button>
  </div>
</template>

<script>
import { Button } from 'vant'
export default {
  name: 'HelloWorld',
  components: { Button },
  data() {
    return {
      msg: 'Welcome to BarTender',
    }
  },
  created() {},
  methods: {
    getId(id) {
      this.$router.push({
        path: `/choice/${id}`,
      })
    },
    click() {
      console.log('1')
    },
  },
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
@-webkit-keyframes focus-in-expand {
  0% {
    letter-spacing: -0.5em;
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}
@keyframes focus-in-expand {
  0% {
    letter-spacing: -0.5em;
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0);
    filter: blur(0);
    opacity: 1;
  }
}

h1 {
  animation-name: focus-in-expand;
  animation-duration: 1s;
  animation-direction: alternate;
  animation-timing-function: ease-in-out;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-4-30 13:17:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
</style>
